In [1]:
%tensorflow_version 1.x
import tensorflow as tf


TensorFlow 1.x selected.


In [0]:
from sklearn.datasets import load_wine
df=load_wine()

In [3]:
df.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [0]:
X=df['data']
y=df['target']

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [0]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train_scaled=scaler.fit_transform(X_train)
x_test_scaled=scaler.transform(X_test)

In [0]:
feat_col=[tf.feature_column.numeric_column("x",shape=[13])]

In [8]:
deep_model_tf=tf.estimator.DNNClassifier(hidden_units=[13,13,13],feature_columns=feat_col,n_classes=3,optimizer=tf.train.GradientDescentOptimizer(0.01))

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpnvxb2t7_', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7f8c41a21940>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [0]:
input_fn = tf.estimator.inputs.numpy_input_fn(x={'x':x_train_scaled},y=y_train,shuffle=True,batch_size=5,num_epochs=5)

In [19]:
deep_model_tf.train(input_fn=input_fn,steps=500)


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpnvxb2t7_/model.ckpt-500
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 500 into /tmp/tmpnvxb2t7_/model.ckpt.
INFO:tensorflow:loss = 0.012991579, step = 500
INFO:tensorflow:global_step/sec: 347.757
INFO:tensorflow:loss = 0.010671733, step = 600 (0.290 sec)
INFO:tensorflow:Saving checkpoints for 624 into /tmp/tmpnvxb2t7_/model.ckpt.
INFO:tensorflow:Loss for final step: 0.41138315.


In [0]:
eval_func=tf.estimator.inputs.numpy_input_fn(x={'x':x_test_scaled},shuffle=True)

In [21]:
predictions=list(deep_model_tf.predict(input_fn=eval_func))

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpnvxb2t7_/model.ckpt-624
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [0]:
mypredictions=[p ['class_ids'][0] for p in predictions]

In [0]:
from sklearn.metrics import confusion_matrix,classification_report

In [24]:
print(confusion_matrix(y_test,mypredictions))

[[7 7 7]
 [5 9 4]
 [8 3 4]]


In [25]:
print(classification_report(y_test,mypredictions))

              precision    recall  f1-score   support

           0       0.35      0.33      0.34        21
           1       0.47      0.50      0.49        18
           2       0.27      0.27      0.27        15

    accuracy                           0.37        54
   macro avg       0.36      0.37      0.36        54
weighted avg       0.37      0.37      0.37        54

